# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f0d71045fcac781223c2b9ebd1e8375"
name = "custom-app"
application_url = "https://seeking-utilization-meter-fourth.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-test-sijan.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_script_tags,read_themes,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://seeking-utilization-meter-fourth.trycloudflare.com/auth/callback",
  "https://seeking-utilization-meter-fourth.trycloudflare.com/auth/shopify/callback",
  "https://seeking-utilization-meter-fourth.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://seeking-utilization-meter-fourth.trycloudflare.com/api"
subpath = "custom-app"
prefix = "apps"

[pos]
embedded = false
